-- MySQL Script generated by MySQL Workbench
-- Mon 09 Feb 2026 10:30:08 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assets` (
  `file_hash` BINARY(32) NOT NULL COMMENT 'SHA256 (檔案識別)',
  `mime_type` VARCHAR(128) NULL DEFAULT NULL COMMENT 'audio/flac, image/jpeg, text/lrc',
  `asset_type` VARCHAR(32) GENERATED ALWAYS AS (SUBSTRING_INDEX(mime_type, '/', 1)) STORED COMMENT '由 mime_type 計算得出 (如 audio)',
  `file_size` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '檔案大小',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '創建時間',
  PRIMARY KEY (`file_hash`));


-- -----------------------------------------------------
-- Table `mydb`.`Image_Metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image_Metadata` (
  `image_hash` BINARY(32) NOT NULL COMMENT '圖片 hash',
  `file_hash` BINARY(32) NOT NULL,
  `width` INT NULL DEFAULT NULL COMMENT '圖片寬度',
  `height` INT NULL DEFAULT NULL COMMENT '圖片高度',
  `dominant_color` VARCHAR(50) NULL DEFAULT NULL COMMENT '圖片色調',
  PRIMARY KEY (`image_hash`, `file_hash`),
  INDEX `fk_Image_Metadata_1_idx` (`file_hash` ASC) VISIBLE,
  CONSTRAINT `fk_Image_Metadata_1`
    FOREIGN KEY (`file_hash`)
    REFERENCES `mydb`.`Assets` (`file_hash`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Audio_Metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audio_Metadata` (
  `pcm_hash` BINARY(32) NOT NULL COMMENT 's32le PCM Hash',
  `parent_hash` BINARY(32) NULL DEFAULT NULL COMMENT '指向 master 的 Hash',
  `quality_score` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '品質評分',
  `bit_depth` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '位元深度',
  `sample_rate` MEDIUMINT UNSIGNED NULL COMMENT '取樣率',
  `channels` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '聲道數',
  `duration` FLOAT UNSIGNED NULL DEFAULT NULL COMMENT '時長 (ms)',
  `integrated_loudness` DECIMAL(5,2) NULL DEFAULT NULL COMMENT 'LUFS 平均響度 e.g. -14.50',
  `true_peak` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pcm_hash`),
  INDEX (`parent_hash` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`parent_hash`)
    REFERENCES `mydb`.`Audio_Metadata` (`pcm_hash`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Text_Metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Text_Metadata` (
  `text_hash` BINARY(32) NOT NULL COMMENT '文本內容 hash',
  `file_hash` BINARY(32) NOT NULL,
  `language` VARCHAR(50) NULL DEFAULT NULL COMMENT '文本語言',
  `encoding` VARCHAR(50) NULL DEFAULT 'utf-8' COMMENT '編碼格式\n',
  `format` ENUM('lrc', 'txt', 'srt', 'ttml') NULL DEFAULT NULL COMMENT 'if is lrc, cache for UI 快速知道要不要顯示動態歌詞介面',
  PRIMARY KEY (`text_hash`, `file_hash`),
  INDEX `fk_Text_Metadata_1_idx` (`file_hash` ASC) VISIBLE,
  CONSTRAINT `fk_Text_Metadata_1`
    FOREIGN KEY (`file_hash`)
    REFERENCES `mydb`.`Assets` (`file_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entities` (
  `id` BINARY(16) NOT NULL,
  `entity_type` ENUM('track', 'album', 'artist', 'work', 'playlist') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artist` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID',
  `name` VARCHAR(255) NOT NULL COMMENT '藝術家名稱',
  `musicbrainz_id` VARCHAR(64) NULL DEFAULT NULL,
  `spotify_id` VARCHAR(64) NULL DEFAULT NULL COMMENT 'spotify 個人頁面 id',
  `ytm_id` VARCHAR(64) NULL DEFAULT NULL COMMENT 'ytm 個人頁面 id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Artist_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID',
  `title` VARCHAR(255) NOT NULL COMMENT '作品名稱',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Work_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Work_Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work_Artists` (
  `work_id` BINARY(16) NOT NULL,
  `artist_id` BINARY(16) NOT NULL,
  `role` VARCHAR(100) NULL DEFAULT NULL COMMENT 'composer,singer,etc',
  PRIMARY KEY (`work_id`, `artist_id`),
  INDEX (`artist_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`work_id`)
    REFERENCES `mydb`.`Work` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`artist_id`)
    REFERENCES `mydb`.`Artist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Track` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID',
  `work_id` BINARY(16) NULL DEFAULT NULL COMMENT '所屬作品 ID',
  `pcm_hash` BINARY(32) NOT NULL DEFAULT NULL COMMENT '播放首選 PCM Hash',
  PRIMARY KEY (`id`, `pcm_hash`),
  INDEX (`work_id` ASC) VISIBLE,
  INDEX (`pcm_hash` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`work_id`)
    REFERENCES `mydb`.`Work` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`pcm_hash`)
    REFERENCES `mydb`.`Audio_Metadata` (`pcm_hash`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Track_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID',
  `title` VARCHAR(255) NOT NULL COMMENT '專輯標題',
  `release_date` DATETIME NULL DEFAULT NULL COMMENT '發行日期',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Album_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Tracks_Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tracks_Album` (
  `track_id` BINARY(16) NOT NULL,
  `album_id` BINARY(16) NOT NULL,
  `position` INT NULL DEFAULT NULL COMMENT 'track 在 album 中的位置',
  `disc_number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`track_id`, `album_id`),
  INDEX (`album_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`track_id`)
    REFERENCES `mydb`.`Track` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`Album` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Track_Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Track_Artists` (
  `track_id` BINARY(16) NOT NULL,
  `artist_id` BINARY(16) NOT NULL,
  `role` VARCHAR(100) NULL DEFAULT NULL COMMENT 'primary / feat / composer',
  `position` INT NULL DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`track_id`, `artist_id`),
  INDEX (`artist_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`track_id`)
    REFERENCES `mydb`.`Track` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`artist_id`)
    REFERENCES `mydb`.`Artist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlists` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID',
  `title` VARCHAR(255) NOT NULL COMMENT '清單名稱',
  `description` TEXT NULL DEFAULT NULL COMMENT '描述文字',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '建立時間',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT '最後更新時間',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Playlists_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Tracks_Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tracks_Playlist` (
  `playlist_id` BINARY(16) NOT NULL COMMENT '清單 ID',
  `track_id` BINARY(16) NOT NULL COMMENT '歌曲 ID',
  `position` INT NULL DEFAULT NULL COMMENT '播放順序',
  `added_at` DATETIME NULL DEFAULT NULL COMMENT '加入時間',
  PRIMARY KEY (`playlist_id`, `track_id`),
  INDEX (`track_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`playlist_id`)
    REFERENCES `mydb`.`Playlists` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`track_id`)
    REFERENCES `mydb`.`Track` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Audio_Assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audio_Assets` (
  `pcm_hash` BINARY(32) NOT NULL,
  `file_hash` BINARY(32) NOT NULL,
  PRIMARY KEY (`pcm_hash`, `file_hash`),
  INDEX (`file_hash` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`pcm_hash`)
    REFERENCES `mydb`.`Audio_Metadata` (`pcm_hash`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`file_hash`)
    REFERENCES `mydb`.`Assets` (`file_hash`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Source_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Source_Data` (
  `id` BINARY(16) NOT NULL COMMENT 'uuid',
  `file_hash` BINARY(32) NOT NULL COMMENT '物理檔案 Hash',
  `source_type` VARCHAR(64) NULL DEFAULT NULL COMMENT 'YTM / Local / CD',
  `original_path` VARCHAR(2048) NULL DEFAULT NULL COMMENT '原始路徑或網址',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '匯入時間',
  `note` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`file_hash`)
    REFERENCES `mydb`.`Assets` (`file_hash`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Images` (
  `entity_id` BINARY(16) NOT NULL,
  `image_hash` BINARY(32) NOT NULL,
  `role` ENUM('front', 'back', 'leaflet', 'medium', 'matrix', 'spine', 'tray', 'sleeve', 'artist_avatar', 'artist_banner', 'artist_logo', 'live', 'studio', 'series_logo', 'thumbnail', 'other') NULL COMMENT '\'cover, cover.back, artist.avatar,\'',
  PRIMARY KEY (`entity_id`, `image_hash`),
  INDEX `fk_Entity_Images_1_idx` (`image_hash` ASC) VISIBLE,
  CONSTRAINT `fk_Entity_Images_1`
    FOREIGN KEY (`image_hash`)
    REFERENCES `mydb`.`Image_Metadata` (`image_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entity_Images_2`
    FOREIGN KEY (`entity_id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Text` (
  `entity_id` BINARY(16) NOT NULL,
  `text_hash` BINARY(32) NOT NULL,
  `role` ENUM('lyrics', 'lyrics_translation', 'lyrics_transliteration', 'description', 'biography', 'liner_notes', 'credits', 'review', 'trivia', 'other') NULL COMMENT '\'lyrics, description, biography\'',
  `language` VARCHAR(16) NULL,
  PRIMARY KEY (`entity_id`, `text_hash`),
  INDEX `fk_Entity_Text_1_idx` (`text_hash` ASC) VISIBLE,
  CONSTRAINT `fk_Entity_Text_1`
    FOREIGN KEY (`text_hash`)
    REFERENCES `mydb`.`Text_Metadata` (`text_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entity_Text_2`
    FOREIGN KEY (`entity_id`)
    REFERENCES `mydb`.`Entities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
